<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
    <PackageId>ConsumerDataRight.ParticipantTooling.MockSolution.TestAutomation</PackageId>
    <Authors />
    <Description>Shared test automation code for Consumer Data Right mock solutions.</Description>
    <Copyright>Copyright (c) 2023 Commonwealth of Australia</Copyright>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/ConsumerDataRight/mock-solution-test-automation</PackageProjectUrl>
    <PackageIcon>cdr-package-logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>cdr;consumer-data-right;open-banking;open-energy</PackageTags>
    <PackageReleaseNotes>https://github.com/ConsumerDataRight/mock-solution-test-automation/releases</PackageReleaseNotes>
    <RepositoryUrl>https://github.com/ConsumerDataRight/mock-solution-test-automation</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Configurations>Debug;Release;Shared</Configurations>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <IncludeSymbols>True</IncludeSymbols>
    <EmbedAllSources>True</EmbedAllSources>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <DebugType>Embedded</DebugType>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <MinVerSkip Condition="'$(Configuration)' == 'Debug'">true</MinVerSkip>
    <!--The tag prefix we use for github and azuredevops is "v". Prefix is case-insensitive—in this example, both v1.2.3 and V1.2.3 would work.-->
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <!--This is the current version released. MinVer will increase the patch by one. This is useful when branch tags are not found-->
    <!--<MinVerMinimumMajorMinor>1.1</MinVerMinimumMajorMinor>-->
    <MinVerDefaultPreReleaseIdentifiers>preview</MinVerDefaultPreReleaseIdentifiers>
    <MinVerVerbosity>detailed</MinVerVerbosity>
    <SonarQubeTestProject>false</SonarQubeTestProject>
    <!--Disable missing XML warning and nullable warnings-->
    <NoWarn>1591,8618,8602,8603,8604,8767</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TF_BUILD)' == 'true' Or '$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\Assets\cdr-package-logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <Visible>false</Visible>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <Visible>false</Visible>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
<ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" Condition="'$(UsingGitHubSource)'=='true'" />
    <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" PrivateAssets="All" Condition="'$(UsingGitHubSource)'!='true'" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Dapper.Contrib" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="jose-jwt" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="MinVer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Exceptions" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.XUnit3" />
    <PackageReference Include="SonarAnalyzer.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="xunit.v3.extensibility.core" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <Target Name="AddMinVerMetaData" AfterTargets="MinVer" Condition="'$(MinVerBuildMetadata)' != ''">
    <PropertyGroup>
      <PackageVersion>$(PackageVersion)-$(MinVerBuildMetadata)</PackageVersion>
      <Version>$(PackageVersion)</Version>
    </PropertyGroup>
  </Target>
</Project>